#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18033
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AutoSendPic.Resource", IsApplication=true)]

namespace AutoSendPic
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int btnExit = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int btnFocus = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int btnSendStart = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int btnToggleFlash = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int surfaceView1 = 2131099653;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int main_btnFocus_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int pref_send_url_key = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int pref_send_url_summary = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int pref_send_url_title = 2131034116;
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preference = 2130968576;
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
